#
# Variables for Azure template Deployment
#
SUBSCRIPTION_ID: xxxxxxxx-xxxxxx-xxxx-xxxxxxxxx
TENANT_ID: xxxxxxxx-xxxxxx-xxxx-xxxxxxxxx
CLIENT_ID: xxxxxxxx-xxxxxx-xxxx-xxxxxxxxx
SERVICE_PRINCIPAL_SECRET: xxxxxx/xxxxxxxx/xxxxxxxxx

# Student_ID lowercase and numbers only
STUDENT_ID: cav

RESOURCE_GROUP: AO-LAB-{{ STUDENT_ID }}

DEFAULT_LOCATION: "Central US"

VNET1: aolab-vnet-{{ STUDENT_ID }}
VNET_SUBNET1: aolab-subnet-{{ STUDENT_ID }}

NODE_NAME: lamp-server
BIGIP_NAME: bigip
NODE_ADDRESS: 10.1.10.80
NODE_USER: f5student
NODE_PASSWORD: f5DEMOs4uLATAM
ALLOWED_SRC_ADDRESS: "0.0.0.0/0"
BIGIP_ADDRESS: 10.1.10.245
ADMINUSERNAME: azureuser
ADMINPASSWORD: f5DEMOs4uLATAM
# BIGIP_LICENSE: RSRZL-KGFSF-WPHJX-ILRNW-FRUDQIQ
