- name: Create Ubuntu resources
  hosts: localhost
  vars:
    local_ip: "empty"
    date: "{{ lookup('pipe', 'date +%Y%m%d') }}"
  vars_files:
    - ./config.yml

  tasks:
  
    - name: THIS CAN TAKE SOME TIME (10 MIN) ... HAVE A COFFEE AND RELAX!
      debug: msg="Starting now @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
      
    - name: Get your Public IP Address
      local_action:
        module: uri
        #url: https://wtfismyip.com/json
        url: http://checkip.amazonaws.com
        return_content: yes
      register: local_ip
      failed_when: not local_ip.content | regex_search ('(\d+).(\d+).(\d+).(\d+)\n')

    - name: Set Public Network Variable
      set_fact:
        ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipsubnet (24,0) }}"
        #ALLOWED_SRC_ADDRESS: "{{ local_ip.content | ipaddr ('host') }}"

    - name: Display Public Network for Security Group - ALLOWED_SRC_ADDRESS
      debug: var=ALLOWED_SRC_ADDRESS
    
    - debug: msg="Finishing ... @ {{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"
