#
# Variables for Azure template Deployment
#
#SUBSCRIPTION_ID: xxxxxxxxx-xxxxxxxxx-xxxxxxxxxxxx
#TENANT_ID: xxxxxxxxx-xxxxxxxxx-xxxxxxxxxxxx
#CLIENT_ID: xxxxxxxxx-xxxxxxxxx-xxxxxxxxxxxx
#SERVICE_PRINCIPAL_SECRET: xxxxxx/xxxxxxxxx/xxxxxx

# Credentials not used in this file in v2. 
# Create a file $HOME/.azure/credentials with the following syntax:
#
# [default]
# subscription_id=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
# client_id=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
# secret=xxxxxxxxxxxxxxxxx
# tenant=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx


# Student_ID lowercase and numbers only
STUDENT_ID: cav

RESOURCE_GROUP: AO-LAB-{{STUDENT_ID}}

#DEFAULT_LOCATION: "Central US"
DEFAULT_LOCATION: "Brazil South"

VNET1: lab-vnet-{{STUDENT_ID}}

SUBNET_MGMT: sub-mgmt-{{STUDENT_ID}}
SUBNET_EXT: sub-ext-{{STUDENT_ID}}
SUBNET_INT: sub-int-{{STUDENT_ID}}

VNET_CIDR: "10.1.0.0/16"
MGMT_PREFIX: "10.1.1.0/24"
EXT_PREFIX: "10.1.10.0/24"
INT_PREFIX: "10.1.20.0/24"

BIGIP_ADDRESS_MGMT: 10.1.1.245
BIGIP_ADDRESS_EXT: 10.1.10.245
BIGIP_ADDRESS_INT: 10.1.20.245

NODE_ADDRESS: 10.1.10.80
NODE_NAME: lamp-server
NODE_USER: f5student
NODE_PASSWORD: f5DEMOs4uLATAM

BIGIP_NAME: bigip
ADMINUSERNAME: azureuser
ADMINPASSWORD: f5DEMOs4uLATAM

ALLOWED_SRC_ADDRESS: "0.0.0.0/0"

# This lab uses a PAYG template for BIG-IP. No need for license
# BIGIP_LICENSE: XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX
