---

- name: Create a VIP, pool and pool members
  hosts: localhost

  vars:
    provider:
      password: f5DEMOs4uLATAM
      server: 10.1.10.245
      user: azureuser
      validate_certs: no
      server_port: 4443

  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: round-robin
        monitors: "/Common/http"
        name: pool_web_ansible
        slow_ramp_time: 120

    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.name }}"
        host: "{{ item.host }}"
        name: "{{ item.name }}"
        pool: pool_web_ansible
        port: 8083
      with_items:
        - host: 10.1.10.80
          name: web01

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: foo-vip
        destination: 10.1.10.245
        name: vip_web_ansible
        pool: pool_web_ansible
        port: 443
        snat: Automap
        profiles:
          - http
          - clientssl
