---

- name: Remove VIP, pool, pool members and nodes
  hosts: localhost

  vars_files:
  - ./bigip.yml

  vars:
    provider:
      user: "{{ ADMINUSERNAME }}"
      password: "{{ ADMINPASSWORD }}"
      server: "{{ BIGIP }}"
      validate_certs: no
      server_port: "{{ MGMT_PORT }}"

  tasks:
    - name: Destroy a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        name: vip_web_ansible
        state: absent

    - name: Destroy a pool
      bigip_pool:
        provider: "{{ provider }}"
        name: pool_web_ansible
        state: absent

    - name: Delete nodes
      bigip_node:
        provider: "{{ provider }}"
        name: "{{ item }}"
        state: absent
      loop:
        - web01
