---

- name: Deploy an App using AS3
  hosts: localhost

  vars:
    provider:
      password: f5DEMOs4uLATAM
      server: 10.1.10.245
      user: azureuser
      validate_certs: no
      server_port: 443
      timeout: 60

  tasks:
    - name: Deploy an AS3 configuration
      bigip_appsvcs_extension:
        content: "{{ lookup('file', '{{ playbook_dir }}/03_ansible-as3.json') }}"
        state: present
        provider: "{{ provider }}" 
