---

- name: Deploy an App using AS3
  hosts: localhost

  vars_files:
  - ./bigip.yml

  vars:
    provider:
      user: "{{ ADMINUSERNAME }}"
      password: "{{ ADMINPASSWORD }}"
      server: "{{ BIGIP }}"
      validate_certs: no
      server_port: "{{ MGMT_PORT }}"
      timeout: 60

  tasks:
    - name: Deploying AS3 configuration
      bigip_appsvcs_extension:
        content: "{{ lookup('file', '{{ playbook_dir }}/as3.json') }}"
        state: present
        provider: "{{ provider }}" 
