---

- name: Remove a Tenant using AS3
  hosts: localhost

  vars:
    provider:
      password: f5DEMOs4uLATAM
      server: 10.1.10.245
      user: azureuser
      validate_certs: no
      server_port: 4443
      timeout: 60

  tasks:
    - name: Remove tenant from AS3 configurations
      bigip_appsvcs_extension:
        tenants:
        - ACME_cloud_ANSIBLE
        state: absent
        provider: "{{ provider }}"
